spring.application.name=moi-go

spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=change-this-secret-key-in-real-env-please-32bytes+
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=1209600000
